"""Dynamic tool persistence and serialization manager."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict

_REGISTRY_DIR = Path(__file__).resolve().parent


def save_dynamic_tool(tool_name: str, code_str: str, schema_dict: Dict[str, Any]) -> Path:
    """Save verified tool code and schema into src/dynamic_tools/tool_<name>.py."""
    file_path = _REGISTRY_DIR / f"tool_{tool_name}.py"
    schema_formatted = json.dumps(schema_dict, indent=4)
    content = f'''# Auto-generated by cada1067 Dynamic Tool Generator
from __future__ import annotations
from typing import Any, Dict, List, Optional, Set

SCHEMA = {schema_formatted}

{code_str}
'''
    file_path.write_text(content, encoding="utf-8")
    return file_path
