# Auto-generated by cada1067 Dynamic Tool Generator
from __future__ import annotations
from typing import Any, Dict, List, Optional, Set

SCHEMA = {
    "type": "function",
    "function": {
        "name": "find_inverters_driving_inverters",
        "description": "Find all inverter (NOT) gates whose output directly drives another inverter gate.",
        "parameters": {
            "type": "object",
            "properties": {}
        }
    }
}

def find_inverters_driving_inverters(self) -> dict:
    self._require_netlist()
    nl = self._netlist
    assert nl is not None

    inverter_pairs = []
    inverters = [node for node in nl.nodes.values() if node.gate_type.lower() == 'not']

    for inverter in inverters:
        output_wire = inverter.output
        for other_inverter in inverters:
            if other_inverter != inverter and output_wire in other_inverter.inputs:
                inverter_pairs.append((inverter, other_inverter))

    return {
        'inverter_pairs': [(inv1.output, inv2.output) for inv1, inv2 in inverter_pairs]
    }
