# Auto-generated by cada1067 Dynamic Tool Generator
from __future__ import annotations
from typing import Any, Dict, List, Optional, Set

SCHEMA = {
    "type": "function",
    "function": {
        "name": "count_odd_input_gates",
        "description": "Counts the number of gates in the design that have an odd number of inputs (such as 1-input NOT/BUF, 3-input gates, etc.).",
        "parameters": {
            "type": "object",
            "properties": {
                "gate_types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "Optional list of gate types to restrict the count to (default: all gate types)."
                }
            },
            "required": []
        }
    }
}

def count_odd_input_gates(self, gate_types: Optional[List[str]] = None) -> dict:
    self._require_netlist()
    nl = self._netlist
    assert nl is not None

    types_set = {t.lower() for t in gate_types} if gate_types else None
    odd_count = 0
    breakdown: Dict[str, int] = {}
    for gate in nl.nodes.values():
        if len(gate.inputs) % 2 == 1:
            if types_set is None or gate.gate_type.lower() in types_set:
                odd_count += 1
                breakdown[gate.gate_type] = breakdown.get(gate.gate_type, 0) + 1

    return {
        'odd_input_gate_count': odd_count,
        'breakdown': breakdown
    }

