# Auto-generated by cada1067 Dynamic Tool Generator
from __future__ import annotations
from typing import Any, Dict, List, Optional, Set

SCHEMA = {
    "type": "function",
    "function": {
        "name": "list_nets_driving_and_or_gates",
        "description": "Lists all nets that drive both an AND gate and an OR gate in the design.",
        "parameters": {
            "type": "object",
            "properties": {
                "and_gate_type": {
                    "type": "string",
                    "description": "The type of AND gate to look for."
                },
                "or_gate_type": {
                    "type": "string",
                    "description": "The type of OR gate to look for."
                }
            },
            "required": [
                "and_gate_type",
                "or_gate_type"
            ]
        }
    }
}

def list_nets_driving_and_or_gates(self, and_gate_type: str, or_gate_type: str) -> dict:
    self._require_netlist()
    nl = self._netlist
    assert nl is not None

    and_gates = set()
    or_gates = set()

    for node in nl.nodes.values():
        if node.gate_type == and_gate_type:
            and_gates.add(node.output)
        elif node.gate_type == or_gate_type:
            or_gates.add(node.output)

    driving_nets = set()
    for node in nl.nodes.values():
        if node.output in and_gates or node.output in or_gates:
            for input_net in node.inputs:
                if input_net in nl.wires:
                    driving_nets.add(input_net)

    return {
        'nets': list(driving_nets)
    }
