# Auto-generated by cada1067 Dynamic Tool Generator
from __future__ import annotations
from typing import Any, Dict, List, Optional, Set

SCHEMA = {
    "type": "function",
    "function": {
        "name": "list_primary_inputs_driving_nor_and_xor_gates",
        "description": "Lists all primary input pins that directly drive at least one NOR gate and at least one XOR gate.",
        "parameters": {
            "type": "object",
            "properties": {}
        }
    }
}

def list_primary_inputs_driving_nor_and_xor_gates(self) -> dict:
    self._require_netlist()
    nl = self._netlist
    assert nl is not None

    primary_inputs_driving_nor = set()
    primary_inputs_driving_xor = set()

    # Identify primary inputs driving NOR gates
    for gate_name, gate in nl.nodes.items():
        if gate.gate_type.lower() == 'nor':
            for input_wire in gate.inputs:
                if input_wire in nl.primary_inputs:
                    primary_inputs_driving_nor.add(input_wire)

    # Identify primary inputs driving XOR gates
    for gate_name, gate in nl.nodes.items():
        if gate.gate_type.lower() == 'xor':
            for input_wire in gate.inputs:
                if input_wire in nl.primary_inputs:
                    primary_inputs_driving_xor.add(input_wire)

    # Find primary inputs that drive both NOR and XOR gates
    result = list(primary_inputs_driving_nor.intersection(primary_inputs_driving_xor))

    return {
        'primary_inputs': result
    }
